### ISSUE TITLE
issue on downloading benchmark dataset

### ISSUE THREAD

**Issue by jinwook31** [pikipity/SSVEP-Analysis-Toolbox#50]
I have an issue downloading the benchmark dataset (dataset = BenchmarkDataset(path = '2016_Tsinghua_SSVEP_database')). The link works when I try directly in Chrome, but not in the script...  Is there a way that I can disable the download process to use manually downloaded datasets?

..\SSVEPAnalysisToolbox\datasets\basedataset.py:174: UserWarning: There is an error when donwloading 'S1' data. So retry (1) after 10 seconds.  warnings.warn("There is an error when donwloading '{:s}' data. So retry ({:n}) after 10 seconds.".format(subject.ID, download_try_count))

**Comment by pikipity** [comment]
You can manually download the data and change the "path". If the toolbox detects data, it will not download them.
